In [13]:
CREATE TABLE first_year_class_totals (
	school_name VARCHAR,
	first_year_total_in_2024 INTEGER,
	first_year_total_in_2025 INTEGER
);

INSERT INTO first_year_class_totals VALUES
	('Campbell University', 191, 202),
	('Charleston School of Law', 272, 241),
	('Duke University', 250, 227),
	('Elon University', 206, 228),
	('North Carolina Central University', 133, 133),
	('University of North Carolina Chapel Hill', 181, 181),
	('University of South Carolina', 226, 221),
	('Wake Forest University', 192, 204);

SELECT *
FROM first_year_class_totals;

/*
Showing the construction of the initial table.
*/

SELECT
	first_year_total_in_2024,
	first_year_total_in_2025,
	first_year_total_in_2025 - first_year_total_in_2024 as difference
FROM first_year_class_totals;

/*
Showing the difference between class totals based on years.
*/

SELECT
	school_name,
	ROUND(AVG(first_year_total_in_2024), 2) AS "2024",
	ROUND(AVG(first_year_total_in_2025), 2) AS "2025",
	ROUND((AVG(first_year_total_in_2025) - AVG(first_year_total_in_2024)) * 100.0 / NULLIF(AVG(first_year_total_in_2025),0), 2) AS percentage_difference
FROM first_year_class_totals
GROUP BY school_name
ORDER BY school_name asc;

/*
Shows the Percentage Difference between the classes, rounded to 2 places.
*/

                                school_name  ...  percentage_difference
0                       Campbell University  ...                   5.45
1                  Charleston School of Law  ...                 -12.86
2                           Duke University  ...                 -10.13
3                           Elon University  ...                   9.65
4         North Carolina Central University  ...                   0.00
5  University of North Carolina Chapel Hill  ...                   0.00
6              University of South Carolina  ...                  -2.26
7                    Wake Forest University  ...                   5.88

[8 rows x 4 columns]

In [36]:
CREATE TABLE demographics (
	school_name VARCHAR,
	total_men_2024 INTEGER,
	total_men_2025 INTEGER,
	total_women_2024 INTEGER,
	total_women_2025 INTEGER,
	total_another_gender_id_2024 INTEGER,
	total_another_gender_id_2025 INTEGER,
	total_prefer_not_to_report_2024 INTEGER,
	total_prefer_not_to_report_2025 INTEGER,
	poc_class_total_2024 INTEGER,
	poc_class_total_2025 INTEGER,
	poc_men_total_2024 INTEGER,
	poc_men_total_2025 INTEGER,
	poc_women_total_2024 INTEGER,
	poc_women_total_2025 INTEGER,
	poc_another_gender_id_2024 INTEGER,
	poc_another_gender_id_2025 INTEGER,
	poc_prefer_not_to_report_2024 INTEGER,
	poc_prefer_not_to_report_2025 INTEGER
	);

INSERT INTO demographics VALUES
	('Campbell University', 71, 84, 116, 117, 0, 0, 4, 1, 46, 49, 17, 21, 29, 28, 0, 0, 0, 0),
	('Charleston School of Law', 79, 80, 189, 151, 0, 0, 4, 0, 39, 37, 9, 8, 30, 29, 0, 0, 0, 0),
	('Duke University', 114, 107, 136, 115, 0, 5, 0, 0, 99, 83, 39, 37, 60, 44, 0, 2, 0, 0),
	('Elon University', 78, 78, 124, 149, 3, 1, 1, 0, 55, 79, 18, 17, 37, 61, 0, 1, 0, 0),
	('North Carolina Central University', 45, 38, 84, 94, 4, 1, 0, 0, 96, 105, 27, 24, 68, 80, 1, 1, 0, 0),
	('University of North Carolina Chapel Hill', 84, 85, 92, 92, 3, 4, 2, 0, 43, 42, 14, 18, 28, 23, 1, 1, 0, 0),
	('University of South Carolina', 117, 121, 109, 100, 0, 0, 0, 0, 38, 32, 20, 16, 18, 16, 0, 0, 0, 0),
	('Wake Forest University', 101, 101, 91, 101, 0, 1, 0, 1, 26, 37, 15, 19, 11, 18, 0, 0, 0, 0);

SELECT *
FROM demographics;

SELECT
    school_name,
    ROUND(AVG(total_men_2024)) AS men_2024,
    ROUND(AVG(total_men_2025)) AS men_2025,
    ROUND(
        (AVG(total_men_2025) - AVG(total_men_2024)) * 100.0 / NULLIF(AVG(total_men_2024), 0),
        2
    ) AS percentage_difference
FROM demographics
GROUP BY school_name
ORDER BY school_name ASC;

/*
This query and the following queries calculate the percentage_difference for men, women, poc, another gender.
*/

SELECT
	school_name,
	ROUND(AVG(total_women_2024)) AS women_2024,
	ROUND(AVG(total_women_2025)) AS women_2025,
	ROUND(
        (AVG(total_women_2025) - AVG(total_women_2024)) * 100.0 / NULLIF(AVG(total_women_2024), 0),
        2
    ) AS percentage_difference_women
FROM demographics
GROUP BY school_name
ORDER BY school_name ASC;

SELECT
	school_name,
	ROUND(AVG(total_another_gender_id_2024)) as gender_2024,
	ROUND(AVG(total_another_gender_id_2025)) as gender_2025,
	ROUND(
		(AVG(total_another_gender_id_2025) - AVG(total_another_gender_id_2025)) * 100.0 / NULLIF(AVG(total_another_gender_id_2024), 0),
		2
	) AS percentage_difference_gender
FROM demographics
GROUP BY school_name
ORDER BY school_name ASC; 

/* This query behaves differently as I explained in the Excel file, because it would result in dividing by zero and it gets into some very complicated math. This issue happens with querying Total Prefer Not To Report, so I won't include that here. */

SELECT
	school_name,
	ROUND(AVG(poc_class_total_2024)) AS poc_2024,
	ROUND(AVG(poc_class_total_2025)) AS poc_2025,
	ROUND(
		(AVG(poc_class_total_2025) - AVG(poc_class_total_2024)) * 100.0 / NULLIF(AVG(poc_class_total_2024), 0),
		2
	) AS percentage_difference_poc
FROM demographics
GROUP BY school_name
ORDER BY school_name ASC;

                                school_name  ...  percentage_difference_poc
0                       Campbell University  ...                       6.52
1                  Charleston School of Law  ...                      -5.13
2                           Duke University  ...                     -16.16
3                           Elon University  ...                      43.64
4         North Carolina Central University  ...                       9.38
5  University of North Carolina Chapel Hill  ...                      -2.33
6              University of South Carolina  ...                     -15.79
7                    Wake Forest University  ...                      42.31

[8 rows x 4 columns]